version: 2.1

workflows: 
    version: 2
    build:
        jobs:
            - build:
                filters:
                    branches: 
                        only:
                            - main
                
jobs:
    build:
        working_directory: ~/ExampleAppplication
        docker:
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@5'
            -restore-cache:
                key: depenancy-cache-{{ checksum "packaage-lock.json"}}
            -run:
                name: install-npm
                command: npm install
            -save-cache:
                key: depenancy-cache-{{ checksum "packaage-lock.json"}}
                paths:
                    - ./node_modules           
